
	      /*This file is automatically generated */
	      package it.unisa.javat;
	          
	      public class VersionBuild {
	        static final public String buildnum = "307";
	        static final public String builduser = "Domenico";
	        static final public String builddate = "10-08-2018 14:06:50";  
	      }
	      